import type { TourStep } from './types';

export const TOUR_STORAGE_PREFIX = 'guided_tour_v1';

export const GUIDED_TOUR_STEPS: TourStep[] = [
  {
    id: 'tab-bar',
    route: '/(tabs)',
    anchorId: 'tour-tab-bar',
    title: 'Your main tabs',
    body: 'Home, Partner, Track, Community, and Analytics — everything lives here.',
    icon: 'apps-outline',
    spotlightShape: 'pill',
    placement: 'above',
  },
  {
    id: 'home-week',
    route: '/(tabs)',
    anchorId: 'tour-home-week',
    title: 'Week at a glance',
    body: 'Swipe through days. Colors show period, fertile window, and logged days.',
    icon: 'calendar-outline',
    spotlightShape: 'pill',
    placement: 'below',
  },
  {
    id: 'home-actions',
    route: '/(tabs)',
    anchorId: 'tour-home-orbs',
    title: 'Quick actions',
    body: 'Log your period, daily symptoms, or take the PCOS screener in one tap.',
    icon: 'add-circle-outline',
    spotlightShape: 'pill',
    placement: 'below',
  },
  {
    id: 'home-profile',
    route: '/(tabs)',
    anchorId: 'tour-home-profile',
    title: 'Profile & settings',
    body: 'Open your avatar for profile, settings, and data export — not in the tab bar.',
    icon: 'person-circle-outline',
    spotlightShape: 'circle',
    placement: 'below',
  },
  {
    id: 'track-calendar',
    route: '/(tabs)/track',
    anchorId: 'tour-track-calendar',
    title: 'Full calendar',
    body: 'See your whole cycle history. Tap any day to log symptoms or period details.',
    icon: 'today-outline',
    placement: 'below',
  },
  {
    id: 'analytics-trends',
    route: '/(tabs)/analytics',
    anchorId: 'tour-analytics-trends',
    title: 'Your trends',
    body: 'Charts built from your logs only. Switch time ranges and tap bars to inspect.',
    icon: 'stats-chart-outline',
    placement: 'below',
  },
  {
    id: 'community-compose',
    route: '/(tabs)/community',
    anchorId: 'tour-community-compose',
    title: 'Community support',
    body: 'Read posts from others and share anonymously when you need peer support.',
    icon: 'people-outline',
    spotlightShape: 'pill',
    placement: 'above',
  },
  {
    id: 'partner-invite',
    route: '/(tabs)/partner',
    title: 'Partner sharing',
    body: 'Optionally invite a partner with a code. You choose exactly what they can see.',
    icon: 'heart-outline',
    placement: 'below',
  },
];
